name = "Scent Craft"
author = "Tinnaphat Somsang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d5f0f89703182a108b76e68c41a193deb3371af7634b698158f39a80900adcb"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
