name = "Scent Craft"
author = "Tinnaphat Somsang"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d606432c85e37fa13108b651f674fe3cfa8495b03bb682b13d9535e917daba6"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
