name = "Scent Craft"
author = "Tinnaphat Somsang"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fedf6147b177c30fc4ed87c43fa8c2ff9eb7f4d2bf837947fe48cbd4a5a6e681"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
