#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 11 22:07:53 ICT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=14
shaderPack=MID ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
enableShaders=true
